paths:
  /products:
    post:
      summary: Create new product
      tags:
        - products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product created successfully
        "400":
          description: Bad request

    get:
      summary: Get all products
      tags:
        - products
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
          description: Number of items per page
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  totalPages:
                    type: integer
                  page:
                    type: integer
                  pagingCounter:
                    type: integer
                  hasPrevPage:
                    type: boolean
                  hasNextPage:
                    type: boolean
                  prevPage:
                    type: integer
                    nullable: true
                  nextPage:
                    type: integer
                    nullable: true
        "404":
          description: No products found

  /products/{id}:
    get:
      summary: Get product by ID
      tags:
        - products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        "200":
          description: A single product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found

    put:
      summary: Update product by ID
      tags:
        - products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product updated successfully
        "404":
          description: Product not found
        "400":
          description: Bad request

    delete:
      summary: Delete product by ID
      tags:
        - products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The product ID
      responses:
        "200":
          description: Product deleted successfully
        "404":
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Name of the product
        photo:
          type: string
          description: Image of the product
        price:
          type: number
          description: Price of the product
        stock:
          type: number
          description: Stock of the product
